version: "3.9"

services:
  mariadb:
    image: mariadb:10.2.38
    container_name: server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: server
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

 
volumes:
  mariadb_data:
